version: 0.2

phases:
  install:
    commands:
      - echo Installing Java 21...
      - yum install -y java-21-amazon-corretto
      - export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version

  build:
    commands:
      - echo Building project...
      - ./mvnw clean package -DskipTests

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - target/*.jar