version: 0.2

env:
  variables:
    JAVA_HOME: /usr/lib/jvm/java-21-amazon-corretto

phases:
  install:
    commands:
      - echo Installing Java 21...
      - yum install -y java-21-amazon-corretto

      # Ensure PATH uses JAVA_HOME
      - export PATH=$JAVA_HOME/bin:$PATH

      - echo JAVA_HOME is $JAVA_HOME
      - java -version

  build:
    commands:
      - echo Building project...

      # Fix permission
      - chmod +x mvnw

      # Run build
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - target/*.jar